### ISSUE TITLE
Form affects buttons

### ISSUE THREAD

**Issue by jonas-kgomo** [Affordance-App/affordance#4]
When you click on sign-in buttons, they are affected by the form. 
Recreate: do no enter email, sign in with Google. 
Expected: refreshes
Actual: asks to 'please fill out this field' in  magic link field.

![fDXACyHKr6](https://user-images.githubusercontent.com/25654848/117072197-c207d880-ad38-11eb-8199-cbfdb3ec5a62.gif)

**Comment by coderinblack08** [comment]
add `type="button"` or remove the oauth buttons from the form

**Comment by chalkedgoose** [comment]
Taking Issue

**Comment by chalkedgoose** [comment]
Actually it might make sense to tackle the issue in #3 or as a follow up @jonas-kgomo 
what do you think?

**Comment by jonas-kgomo** [comment]
Sounds awesome, I just fixed it into #9
